In [1]:
import numpy as np 


In [2]:
import numpy as np

students = np.array([
    "Rahul", "Priya", "Amit", "Neha", "Rohit"
])

marks = np.array([
    [85, 78, 90, 88],
    [92, 89, 95, 91],
    [65, 70, 0, 72],
    [0, 0, 0, 0],
    [35, 40, 38, 42]
])

print("===== STUDENT MARKS ANALYSIS =====")

print("\nStudents:")
print(students)

print("\nMarks:")
print(marks)

total = np.sum(marks, axis=1)
print("\nTotal Marks:")
print(total)

percentage = total / 4
print("\nPercentage:")
print(percentage)

average = np.mean(marks)
print("\nAverage Marks of Class:")
print(average)

print("\nHighest Marks:")
print(np.max(marks))

print("\nLowest Marks:")
print(np.min(marks))

print("\nSubject Wise Average:")
print(np.mean(marks, axis=0))

topper = np.argmax(total)
print("\nTopper:")
print(students[topper])

print("\nPass/Fail Students:")

for i in range(len(students)):
    if np.all(marks[i] >= 40):
        print(students[i], "Pass")
    else:
        print(students[i], "Fail")

===== STUDENT MARKS ANALYSIS =====

Students:
['Rahul' 'Priya' 'Amit' 'Neha' 'Rohit']

Marks:
[[85 78 90 88]
 [92 89 95 91]
 [65 70  0 72]
 [ 0  0  0  0]
 [35 40 38 42]]

Total Marks:
[341 367 207   0 155]

Percentage:
[85.25 91.75 51.75  0.   38.75]

Average Marks of Class:
53.5

Highest Marks:
95

Lowest Marks:
0

Subject Wise Average:
[55.4 55.4 44.6 58.6]

Topper:
Priya

Pass/Fail Students:
Rahul Pass
Priya Pass
Amit Fail
Neha Fail
Rohit Fail
